# Copyright (c) 2018 Guo Xiang
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

PKG_NAME := EasyCpp
PKG_PATH := EasyCpp

SRC := \
  Implement/Debug/Debug.cpp \
  Implement/Debug/DebugPrintf.cpp \
  Implement/Debug/DebugSharedPtr.cpp \
  Implement/Exception/Exception.cpp \
  Implement/Regex/Regex.cpp \
  Implement/Regex/RegexHandlerGroup.cpp \
  Implement/String/CommonString.cpp \
  Implement/String/Json.cpp \
  Implement/String/StringJson.cpp \
  Implement/String/StringBase64.cpp \
  Implement/String/CharSplit.cpp \
  Implement/String/CharSplitRev.cpp \
  Implement/String/TokenSplit.cpp \
  Implement/String/TokenSplitRev.cpp \
  Implement/String/LineSplit.cpp \
  Implement/String/LineSplitRev.cpp \
  Implement/String/StringSplit.cpp \
  Implement/String/StringSplitRev.cpp \
  Implement/String/SplitWrapper.cpp \

include $(TEMPLATE)

